# Generated by Django 3.1.1 on 2020-11-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.ImageField(default='default.jpg', upload_to='resumes'),
        ),
    ]
