# Generated by Django 3.1.1 on 2020-11-24 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_resume 2'),
        ('users', '0004_auto_20201105_2002 2'),
        ('users', '0004_auto_20201105_2002'),
        ('users', '0003_auto_20201102_1723 2'),
    ]

    operations = [
    ]
