# Generated by Django 3.1.1 on 2020-11-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_merge_20201124_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='resume',
            field=models.FileField(default=None, upload_to='resumes'),
        ),
    ]
