# Generated by Django 3.1.1 on 2020-09-28 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_connecting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pay',
            field=models.CharField(max_length=200),
        ),
    ]
