# Generated by Django 3.1.1 on 2020-10-02 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_connecting', '0002_auto_20200928_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='post',
            name='last_name',
        ),
    ]
