# Generated by Django 3.1.1 on 2020-10-21 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case_connecting', '0005_application_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='post',
        ),
    ]
