# Generated by Django 3.1.1 on 2020-10-21 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_connecting', '0006_remove_application_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='case_connecting.post'),
            preserve_default=False,
        ),
    ]
