# Generated by Django 3.1.1 on 2020-10-22 20:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('case_connecting', '0010_auto_20201021_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='date_applied',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='application',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='case_connecting.post'),
        ),
    ]
