# Generated by Django 3.1.1 on 2020-10-26 19:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('case_connecting', '0012_savepost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SavePost',
            new_name='Save',
        ),
    ]
