# Generated by Django 3.1.1 on 2020-11-09 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('case_connecting', '0014_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='application',
        ),
        migrations.AddField(
            model_name='chat',
            name='app',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='case_connecting.application'),
        ),
    ]
